
name: Release

permissions:
  contents: read

on:
  push:
#    tags:
#      - v[0-9]+.*

jobs:

  upload-companion:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v6
      - run: ls -l
      - run: ls -l companion-module-scoreboard-scoreboard
      - uses: actions/setup-node@v3
        with: 
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: companion-module-scoreboard-scoreboard/yarn.lock
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./companion-module-scoreboard-scoreboard
      - name: Build Companion Module
        run: yarn companion-module-build
        working-directory: ./companion-module-scoreboard-scoreboard

